---
- name: Fortigate Policy

  hosts: fortigates

  collections:
    - fortinet.fortios

  tasks:

    - name: Firewall Policy

      fortios_firewall_policy:

        vdom: root

        state: present

        firewall_policy:

          policyid: 100

          name: APP_TO_DB

          action: accept

          srcintf:
            - name: port1

          dstintf:
            - name: port2

          srcaddr:
            - name: APP

          dstaddr:
            - name: DB

          service:
            - name: HTTPS

          schedule: always