---
- name: Create FMC Access Rule

  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - cisco.fmcansible

  vars:

    fmc_host: 192.168.1.50
    fmc_username: admin
    fmc_password: Cisco123!

    access_policy: Enterprise_ACP

    rule_name: APP_TO_DB

    source_network: APP
    destination_network: DB

  tasks:

    - name: Create Access Control Rule

      fmc_configuration:

        operation: upsertAccessRule

        data:

          acpName: "{{ access_policy }}"

          name: "{{ rule_name }}"

          action: ALLOW

          enabled: true

          sourceNetworks:

            objects:
              - name: "{{ source_network }}"
                type: Network

          destinationNetworks:

            objects:
              - name: "{{ destination_network }}"
                type: Network