---
- name: Palo Alto Policy

  hosts: paloaltos

  collections:
    - paloaltonetworks.panos

  tasks:

    - name: Security Policy

      panos_security_rule:

        rule_name: APP_TO_DB

        source_zone:
          - TRUST

        destination_zone:
          - DMZ

        source_ip:
          - 10.1.1.10

        destination_ip:
          - 10.2.2.20

        application:
          - ssl

        action: allow