---
- name: Verify VLAN

  cisco.ios.ios_command:

    commands:
      - show vlan brief

  register: vlan_check

- name: Validate deployment

  assert:

    that:
      - vlan_name in vlan_check.stdout[0]

    fail_msg: "VLAN verification failed"