---
- name: Validate Interface Name

  assert:

    that:
      - interface_name | length > 0

    fail_msg: "Interface Name Missing"

- name: Validate Admin State

  assert:

    that:
      - admin_state in ['', 'up', 'down']

    fail_msg: "admin_state must be up or down"

- name: Validate Description

  assert:

    that:
      - description is string

    fail_msg: "Description must be string"
