---
- name: Delete VLAN

  hosts: cisco_switches

  collections:
    - cisco.ios

  vars:
    vlan_id: 300

  tasks:
    - name: Delete VLAN

      ios_vlans:

        config:
          - vlan_id: "{{ vlan_id }}"

        state: deleted
