---
- name: Verify ACL

  cisco.ios.ios_command:

    commands:
      - show access-lists

  register: acl_output

- name: Validate ACL

  assert:

    that:
      - acl_name in acl_output.stdout[0]

    fail_msg: "ACL verification failed"
