---
- name: ACL Create

  hosts: cisco_routers

  collections:
    - cisco.ios

  tasks:

    - name: ACL
      ios_acls:

        config:

          - afi: ipv4

            acls:

              - name: ATM_ACCESS

                aces:

                  - sequence: 10

                    grant: permit

                    source:
                      address: 10.1.1.0
                      wildcard_bits: 0.0.0.255

                    destination:
                      address: 10.2.2.0
                      wildcard_bits: 0.0.0.255