all:
  children:

    cisco_switches:
      hosts:
        SW1:
          ansible_host: 192.168.1.10

    cisco_routers:
      hosts:
        R1:
          ansible_host: 192.168.1.20

    fortigates:
      hosts:
        FGT1:
          ansible_host: 192.168.1.30

    paloaltos:
      hosts:
        PA1:
          ansible_host: 192.168.1.40

    fmcs:
      hosts:
        FMC1:
          ansible_host: 192.168.1.50
