---
- name: Interface Description

  hosts: cisco_switches

  collections:
    - cisco.ios

  vars:

    interface: GigabitEthernet1/0/5

    description: Connected_To_Server

  tasks:

    - name: Configure Description

      ios_interfaces:

        config:

          - name: "{{ interface }}"
            description: "{{ description }}"
