---
- name: Configure BGP Neighbor

  hosts: cisco_routers
  gather_facts: no

  collections:
    - cisco.ios

  vars:

    local_as: 65001

    neighbor_ip: 192.168.100.2
    remote_as: 65002

    description: ISP_PEER

  tasks:

    - name: Configure BGP Neighbor

      ios_config:

        parents:
          - router bgp {{ local_as }}

        lines:
          - neighbor {{ neighbor_ip }} remote-as {{ remote_as }}
          - neighbor {{ neighbor_ip }} description {{ description }}